/* This file is generated by src/sync-app-blueprints.mjs. */

export const blueprints = [
  {
    "slug": "lawn-care-service",
    "name": "GreenStripe Lawn Care",
    "eyebrow": "Lawn Care Service",
    "summary": "GreenStripe keeps yards crisp, healthy, and party-ready with mowing, edging, seasonal cleanups, and friendly crews who actually close the gate.",
    "logo": "/blueprints/lawn-care-service/assets/logo.png",
    "logoWidth": 1200,
    "logoHeight": 260,
    "hero": "/blueprints/lawn-care-service/assets/hero.jpg",
    "heroWidth": 1920,
    "heroHeight": 1080,
    "alt": "A lawn care professional trimming a crisp green front lawn.",
    "path": "/api/blueprints/lawn-care-service/blueprint.json",
    "layoutVariant": "route-plan",
    "releaseStatus": "approved"
  },
  {
    "slug": "pressure-washing-service",
    "name": "BrightJet Exterior Cleaning",
    "eyebrow": "Pressure Washing And Soft Washing Service",
    "summary": "BrightJet cleans driveways, siding, patios, fences, and storefronts with smart pressure, soft-wash care, and crews who treat your place like it has company...",
    "logo": "/blueprints/pressure-washing-service/assets/logo.png",
    "logoWidth": 1200,
    "logoHeight": 260,
    "hero": "/blueprints/pressure-washing-service/assets/hero.jpg",
    "heroWidth": 1920,
    "heroHeight": 1080,
    "alt": "A professional pressure washing technician cleaning a residential driveway beside a bright suburban home.",
    "path": "/api/blueprints/pressure-washing-service/blueprint.json",
    "layoutVariant": "before-after-quote",
    "releaseStatus": "approved"
  },
  {
    "slug": "window-cleaning",
    "name": "ClearPane Window Care",
    "eyebrow": "Window Cleaning Service",
    "summary": "ClearPane handles interior glass, exterior panes, screens, tracks, and storefront touch-ups with tidy crews, careful edges, and squeegee lines that know...",
    "logo": "/blueprints/window-cleaning/assets/logo.png",
    "logoWidth": 1200,
    "logoHeight": 260,
    "hero": "/blueprints/window-cleaning/assets/hero.jpg",
    "heroWidth": 1920,
    "heroHeight": 1080,
    "alt": "A professional window cleaner using a squeegee on large residential windows in bright daylight.",
    "path": "/api/blueprints/window-cleaning/blueprint.json",
    "layoutVariant": "checklist-urgency",
    "releaseStatus": "approved"
  }
] as const;
